export const CONTENTFUL_BASE_URL = process.env.REACT_APP_CONTENTFUL_BASE_URL+"/";
export const CONTENTFUL_SPACE_ID = process.env.REACT_APP_CONTENTFUL_SPACE_ID;
export const CONTENTFUL_ACCESS_TOKEN = process.env.REACT_APP_CONTENTFUL_ACCESS_TOKEN;
